name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: azure/docker-login@v1
        with:
           login-server: ${{ secrets.ACR_ENDPOINT }}
           username: ${{ secrets.ACR_USERNAME }}
           password: ${{ secrets.ACR_PASSWORD }}
      - run: |
          docker build . --file prod.Dockerfile -t ${{ secrets.ACR_ENDPOINT }}/api-test:latest
          docker push ${{ secrets.ACR_ENDPOINT }}/api-test:latest
      # Set the target AKS cluster.
      - uses: Azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: api-test-cluster
          resource-group: api_test

      - uses: Azure/k8s-create-secret@v1.1
        with:
          container-registry-url: apitestflask.azurecr.io
          container-registry-username: ${{ secrets.ACR_USERNAME }}
          container-registry-password: ${{ secrets.ACR_PASSWORD }}
          secret-name: api-test-k8s-secret

      - uses: Azure/k8s-deploy@v3.1
        with:
          action: deploy
          manifests: |
            k8s/deployment.yaml
          images: |
            apitestflask.azurecr.io/api-test:latest
          imagepullsecrets: |
            api-test-k8s-secret      
